options:

  # do we use https? (only use behind reverse proxy that adds https)
  https: true

  # endpoint to use for the xml
  endpoint: "/miiverse/xml"

  # port to use for the server
  port: 5432

  # basically how much work should it take the cpu of your server
  # to compute the hashes of servicetokens. the higher it is, the
  # more work it takes
  hashCost: 8

  # this can either be what it is now, which is a boolean,
  # or it can be a url that directs to an endpoint which returns
  # a response like this:
  # 
  # inMaintenance: false
  # 
  # (in yaml)
  # 
  maintenance: false

  # set this to true to always use the discovery endpoint
  # specified below in the endpoints section
  overrideDiscovery: false

  cache:

    # timeout in seconds for the automatic endpoint method
    autoTimeout: 1

  # this can be either be what is is now, which is
  # a map of hashed servicetokens encoded in hexadecimal to a map
  # with a reason, or a url to an endpoint on a server that returns a response like this:
  #
  # one-servicetoken:
  #   reason: "haha-yes"
  #
  # two-servicetoken:
  #   reason: "haha-yes"
  # 
  # (with the hexadecimal hashed tokens grabbed from the log) (in yaml)
  # 
  bans:

    token-goes-here:
      reason: "haha-yes"

# groups of sets of endpoints that certain servicetokens point to
endpoints:

  # this group must always be here
  default:
    discovery: "discovery.your-host.xyz"
    api: "api.your-host.xyz"
    wiiu: "wiiu.your-host.xyz"
    3ds: "3ds.your-host.xyz"

  # another optional group
  group-name:
    discovery: "discovery.your-host.xyz"
    api: "api.your-host.xyz"
    wiiu: "wiiu.your-host.xyz"
    3ds: "3ds.your-host.xyz"

# contains servicetokens and the group they match to
# all servicetokens go to the default group unless otherwise specified
groupdefs:

  # a servicetoken group definition. any client with servicetoken-one uses the endpoints in group-name
  servicetoken-one: "group-name"
